= User Installation Guide

== Getting Started

Before installing the Watcher operator you first need a functional
OpenShift installation with the required Openstack operators,
including the Telemetry operator. The following links point
to documents detailing how to create this required starting environment:

* https://github.com/openstack-k8s-operators/openstack-operator[Openstack Operator]
* https://github.com/openstack-k8s-operators/telemetry-operator[Telemetry Operator]
* https://kubernetes.io/docs/concepts/extend-kubernetes/operator/[Kubernetes operators]
* https://prometheus.io/[Prometheus metrics]

A CRC (https://crc.dev/docs/introducing/[Code Ready Containers]) installation is
adequade for a developer environment. To verify that the environment set up is ready,
log in to the Kubernetes/Openshift environment:

[,console]
----
$ oc login -u <username> -p <password> https://api.crc.testing:6443 --insecure-skip-tls-verify=true
----

Then access the Openstack client and verify the service endpoints are available:

[,console]
----
$ oc rsh openstackclient

$ openstack endpoint list
+----------------------------------+-----------+--------------+--------------+---------+-----------+----------------------------------------------------------+
| ID                               | Region    | Service Name | Service Type | Enabled | Interface | URL                                                      |
+----------------------------------+-----------+--------------+--------------+---------+-----------+----------------------------------------------------------+
| 0e72234df99144c3b7e13a62cd42e1a5 | regionOne | keystone     | identity     | True    | internal  | http://keystone-internal.openstack.svc:5000              |
| 139b5c649f074eae874ca2d8a3b7fdcb | regionOne | glance       | image        | True    | public    | https://glance-default-public-openstack.apps-crc.testing |
| 1c6ff2b6f2b54a13a8fefc9dacb8f4a9 | regionOne | neutron      | network      | True    | public    | https://neutron-public-openstack.apps-crc.testing        |
| 4bb6dde288a64c08bc2cd8e2d714aa6d | regionOne | glance       | image        | True    | internal  | http://glance-default-internal.openstack.svc:9292        |
| 6dfd4ac8fae2485580f626d743603c05 | regionOne | keystone     | identity     | True    | public    | https://keystone-public-openstack.apps-crc.testing       |
| 98e631462d2f4828a55e558f36e23e2f | regionOne | neutron      | network      | True    | internal  | http://neutron-internal.openstack.svc:9696               |
| 9a6be9fccf3e42cd8b3205a9c1d88114 | regionOne | placement    | placement    | True    | internal  | http://placement-internal.openstack.svc:8778             |
| aa4363e8f74641ce9a53c14fd4ce8184 | regionOne | placement    | placement    | True    | public    | https://placement-public-openstack.apps-crc.testing      |
| b313c0ce41b840a884b8e0ac4a5a819f | regionOne | cinderv3     | volumev3     | True    | public    | https://cinder-public-openstack.apps-crc.testing/v3      |
| ccadeae4322346fe9feee6bb0677b014 | regionOne | nova         | compute      | True    | internal  | http://nova-internal.openstack.svc:8774/v2.1             |
| dfac9cb0706d411b8c90c6df264fb575 | regionOne | nova         | compute      | True    | public    | https://nova-public-openstack.apps-crc.testing/v2.1      |
| e8314601b5184f74b99b0815e1d57d5e | regionOne | cinderv3     | volumev3     | True    | internal  | http://cinder-internal.openstack.svc:8776/v3             |
+----------------------------------+-----------+--------------+--------------+---------+-----------+----------------------------------------------------------+
----

Now verify that Telemetry operator with Prometheus metric storage is ready:

[,console]
----
$ oc get telemetry
NAME        STATUS   MESSAGE
telemetry   True     Setup complete

$ oc get metricstorage
NAME             STATUS   MESSAGE
metric-storage   True     Setup complete

$ oc get route metric-storage-prometheus
NAME                        HOST/PORT                                              PATH   SERVICES                    PORT   TERMINATION     WILDCARD
metric-storage-prometheus   metric-storage-prometheus-openstack.apps-crc.testing          metric-storage-prometheus   web    edge/Redirect   None
----

Prometheus metrics will be viewable in a web browser at the `HOST/PORT` address returned above. ie:
https://metric-storage-prometheus-openstack.apps-crc.testing.

== Installing the Operator

.Procedure

. Now that you have a ready working environment, you can install the Watcher Operator.
First, create a `watcher-operator.yaml` file:
+
----
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: watcher-operator-index
  namespace: openstack-operators
spec:
  image: quay.io/openstack-k8s-operators/watcher-operator-index:latest
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openstack
  namespace: openstack-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: watcher-operator
  namespace: openstack-operators
spec:
  name: watcher-operator
  channel: alpha
  source: watcher-operator-index
  sourceNamespace: openstack-operators
----
+
. With cluster-admin permissions in Openshift run:
+
----
$ oc apply -f watcher-operator.yaml
catalogsource.operators.coreos.com/watcher-operator-index created
operatorgroup.operators.coreos.com/openstack unchanged
subscription.operators.coreos.com/watcher-operator created
----
+
. Check that the operator is installed:
+
----
$ oc get subscription.operators.coreos.com/watcher-operator -n openstack-operators
NAME               PACKAGE            SOURCE                   CHANNEL
watcher-operator   watcher-operator   watcher-operator-index   alpha

$ oc get pod -l openstack.org/operator-name=watcher -n openstack-operators
NAME                                                  READY   STATUS    RESTARTS   AGE
watcher-operator-controller-manager-dd95db756-kslw9   2/2     Running   0          44s
----

== Deploying the Watcher Service

Now, you will need to create a Watcher Custom Resource based on the `Watcher CRD`.

.Procedure

. Use the following commands to _view_ the `Watcher CRD` definition and specification schema:
+
----
$ oc describe crd watcher

$ oc explain watcher.spec
----
+
. Add a `WatcherPassword` field to the `Secret` created as part of the ControlPlane deployment as explained in https://docs.redhat.com/en/documentation/red_hat_openstack_services_on_openshift/18.0/html/deploying_red_hat_openstack_services_on_openshift/assembly_preparing-RHOCP-for-RHOSO#proc_providing-secure-access-to-the-RHOSO-services_preparing[Providing secure access to the Red Hat OpenStack Services on OpenShift services]. Then `oc apply` the updated file and check the `WatcherPassword` is included.
+
----
$ oc apply -f <secret file> -n openstack

$ oc describe secret osp-secret -n openstack | grep Watcher
WatcherPassword:                  9 bytes
----
+
. Create a file on your workstation named `watcher.yaml` to define the Watcher CR. Your file should contain parameters similar to the example below:
+
----
apiVersion: watcher.openstack.org/v1beta1
kind: Watcher
metadata:
  name: watcher
spec:
  databaseInstance: "openstack"
  secret: <name of the secret with the credentials of the ControlPlane deploy>
  tls:
    caBundleSecretName: "combined-ca-bundle"
----
+
For futher context,
https://docs.redhat.com/en/documentation/red_hat_openstack_services_on_openshift/18.0/html/deploying_red_hat_openstack_services_on_openshift/assembly_creating-the-control-plane#proc_creating-the-control-plane_controlplane[Creating the control plane] references similar commands and procdure to explain how to define an OpenStackControlPlane custom resource (CR).
+
. `oc apply` to configure Watcher
+
----
$ oc apply -f watcher.yaml -n openstack
watcher.watcher.openstack.org/watcher configured
----
+
. To check if the service status, run:
+
----
$ oc wait -n openstack --for condition=Ready --timeout=300s Watcher watcher
watcher.watcher.openstack.org/watcher condition met
----
+
where `Watcher` refers to the _kind_ and `watcher` refers to the name of the CR.
. Check that the watcher service has been registered in list of keystone services with command:
+
----
$ oc rsh openstackclient openstack service list
+----------------------------------+------------+-------------+
| ID                               | Name       | Type        |
+----------------------------------+------------+-------------+
| 1470e8d6019446a1bcdfdb6dc55f3f6a | nova       | compute     |
| 41d60e1c678142cf8e5daf7a82af1864 | neutron    | network     |
| 5b0d95d1c08e4deb832815addd859924 | ceilometer | Ceilometer  |
| 7e081cb4928945d7aa41d1622f7b8586 | cinderv3   | volumev3    |
| 8d7ee56ca2bb4dba999d67580909dd90 | glance     | image       |
| c3348e10fb414780988fbbceac9c4b5f | watcher    | infra-optim |
| db60453eca65409bbb0b61f4295c66ec | placement  | placement   |
| fa717124fbcb4d708ba4c41c9109df81 | keystone   | identity    |
+----------------------------------+------------+-------------+
----
